# Generated by Django 5.2.1 on 2025-06-02 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
        ('properties', '0003_building_agent_building_caretaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parking_slots', to='properties.building'),
        ),
    ]
