# Generated by Django 5.2.1 on 2025-05-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('mpesa', 'M-PESA'), ('bank', 'Bank Transfer'), ('airtel', 'Airtel Money'), ('tkash', 'T-Kash'), ('manual', 'Manual')], default='mpesa', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
