# Generated by Django 5.2.1 on 2025-06-02 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0001_initial'),
        ('properties', '0003_building_agent_building_caretaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='properties.building'),
        ),
    ]
