# Generated by Django 5.2.1 on 2025-05-31 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_buildings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='building',
            name='caretaker',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'caretaker'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caretaker_buildings', to=settings.AUTH_USER_MODEL),
        ),
    ]
