# Generated by Django 5.2.1 on 2025-05-31 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('properties', '0003_building_agent_building_caretaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.building'),
        ),
    ]
