# Generated by Django 5.2.1 on 2025-05-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('rules', 'Rules'), ('notice', 'Notice'), ('manual', 'Manual'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
